---
title: "Gov 50 Final Project"
author: "Ali Khan"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

> This data is based off of https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Star.html

# Shifted Focus

I have shifted my focus due to a lack of data on my initial project idea.  

## Variable Descriptions

tmathssk - cumulative math scaled score

treadssk - cumulative reading scaled score

classk - type of class, factor with varying levels (regular/small.class/regular.with.aide)

totexpk - cumulative years of teaching experience

sex - boy/girl

freelunk - qualified for free lunch?

race - white/black/other

schidkn - school indicator variable

# Data Background

This data was collected through a cross-sectional study from 1985-1989 under the STAR (Student-Teacher Achievement Ratio) initiative that randomly assigned these students into 3 groups of varying class sizes: small (13-17 students per teacher), regular (22-25 students per teacher), & regular w/ aide (22-25 students along with a full-time teacher's aide). Teachers were also randomly assigned a classroom to instruct, and this study conducted the experiment with kindergarten students until the end of their third grade.  


```{r}
library(tidyverse)
library(gov50data)
library(infer)
library(ggplot2)

star <- read_csv("data/Star.csv")

mathplot <- star |> 
  ggplot(aes(x = classk, y = tmathssk, color = classk)) +
  geom_boxplot() + 
  labs(x = "Class Size",
       y = "Cumulative Math Score")

mathplot

readingplot <- star |> 
  ggplot(aes(x = classk, y = treadssk, color = classk)) +
  geom_boxplot() + 
  labs(x = "Class Size",
       y = "Cumulative Reading Score")

readingplot


math_fit_1 <- lm(data = star, tmathssk ~ classk)

math_fit_1 |>
  broom::tidy() |>
  select(term, estimate) |>  
  knitr::kable(digits = 2)


```
Created two boxplots to compare the results of the 3 class sizes and their performance on reading and math test scores. These visualizations support the hypothesis of smaller class sizes being the most effective for student performance on tests. Smaller class sizes have the highest median in both test scores, but it's interesting to note that the minimum of small class sizes is lower than reg class sizes with aides for testing results.

From the linear regression output, the regular class has an estimated cumulative math score of 483.26 points. We can infer that on average, students in the regular class with an aide scores 0.25 points less than students in the regular class  and on average, students in the small class score 8.21 points higher than those in students in regular classes with aides. 
